package org.kie.uberfire.social.activities.drools
import org.kie.uberfire.social.activities.model.SocialActivitiesEvent;

global org.kie.uberfire.social.activities.drools.SocialTimelineRulesQuery queryAPI;
global java.util.List socialEvents;
global java.util.List socialEvents;
global java.lang.String filter;
rule "filterTimelineRecentAssets"
when
  $result:SocialActivitiesEvent(getLinkTarget() contains filter) from queryAPI.getTypeCached("RESOURCE_ADDED_EVENT",
                                                                                             "RESOURCE_UPDATE_EVENT",
                                                                                             "NEW_REPOSITORY_EVENT",
                                                                                             "NEW_ORGANIZATIONAL_UNIT",
                                                                                             "ORGANIZATIONAL_UNIT_UPDATED",
                                                                                             "REPO_ADDED_TO_ORGANIZATIONAL_UNIT",
                                                                                             "REPO_REMOVED_FROM_ORGANIZATIONAL_UNIT",
                                                                                             "NEW_PROJECT")
  eval( true )
then
  socialEvents.add($result);
end